#' @title Aliases for underscore style
#'
#' @description
#' mlr is written in camel case, but many R users prefer the
#' underscore style. These aliases provide an underscore
#' version of mlr functions.
#'
#' @export
add_rr_measure <- mlr::addRRMeasure
analyze_feat_sel_result <- mlr::analyzeFeatSelResult
as_rocr_prediction <- mlr::asROCRPrediction
calculate_confusion_matrix <- mlr::calculateConfusionMatrix
bootstrap_b632 <- mlr::bootstrapB632
bootstrap_b632_plus <- mlr::bootstrapB632plus
bootstrap_oob <- mlr::bootstrapOOB
calculate_roc_measures <- mlr::calculateROCMeasures
cap_large_values <- mlr::capLargeValues
configure_mlr <- mlr::configureMlr
convert_bmr_to_rank_matrix <- mlr::convertBMRToRankMatrix
convert_mlbench_obj_to_task <- mlr::convertMLBenchObjToTask
create_dummy_features <- mlr::createDummyFeatures
create_spatial_resampling_plots <- mlr::createSpatialResamplingPlots
drop_features <- mlr::dropFeatures
estimate_relative_overfitting <- mlr::estimateRelativeOverfitting
estimate_residual_variance <- mlr::estimateResidualVariance
extract_fda_features <- mlr::extractFDAFeatures
extract_fda_fourier <- mlr::extractFDAFourier
extract_fda_fpca <- mlr::extractFDAFPCA
extract_fda_multi_res_features <- mlr::extractFDAMultiResFeatures
extract_fda_wavelets <- mlr::extractFDAWavelets
filter_features <- mlr::filterFeatures
friedman_post_hoc_test_bmr <- mlr::friedmanPostHocTestBMR
friedman_test_bmr <- mlr::friedmanTestBMR
generate_calibration_data <- mlr::generateCalibrationData
generate_crit_differences_data <- mlr::generateCritDifferencesData
generate_feature_importance_data <- mlr::generateFeatureImportanceData
generate_filter_values_data <- mlr::generateFilterValuesData
generate_hyper_pars_effect_data <- mlr::generateHyperParsEffectData
generate_learning_curve_data <- mlr::generateLearningCurveData
generate_partial_dependence_data <- mlr::generatePartialDependenceData
generate_thresh_vs_perf_data <- mlr::generateThreshVsPerfData
get_bmr_aggr_performances <- mlr::getBMRAggrPerformances
get_bmr_feat_sel_results <- mlr::getBMRFeatSelResults
get_bmr_filtered_features <- mlr::getBMRFilteredFeatures
get_bmr_learner_ids <- mlr::getBMRLearnerIds
get_bmr_learners <- mlr::getBMRLearners
get_bmr_learner_short_names <- mlr::getBMRLearnerShortNames
get_bmr_measure_ids <- mlr::getBMRMeasureIds
get_bmr_measures <- mlr::getBMRMeasures
get_bmr_models <- mlr::getBMRModels
get_bmr_performances <- mlr::getBMRPerformances
get_bmr_predictions <- mlr::getBMRPredictions
get_bmr_task_descriptions <- mlr::getBMRTaskDescriptions
get_bmr_task_descs <- mlr::getBMRTaskDescs
get_bmr_task_ids <- mlr::getBMRTaskIds
get_bmr_tune_results <- mlr::getBMRTuneResults
get_caret_param_set <- mlr::getCaretParamSet
get_class_weight_param <- mlr::getClassWeightParam
get_conf_matrix <- mlr::getConfMatrix
get_default_measure <- mlr::getDefaultMeasure
get_failure_model_dump <- mlr::getFailureModelDump
get_failure_model_msg <- mlr::getFailureModelMsg
get_feat_sel_result <- mlr::getFeatSelResult
get_feature_importance <- mlr::getFeatureImportance
get_feature_importance_learner <- mlr::getFeatureImportanceLearner
get_filtered_features <- mlr::getFilteredFeatures
get_filter_values <- mlr::getFilterValues
get_hyper_pars <- mlr::getHyperPars
get_learner_id <- mlr::getLearnerId
get_learner_model <- mlr::getLearnerModel
get_learner_packages <- mlr::getLearnerPackages
get_learner_param_set <- mlr::getLearnerParamSet
get_learner_par_vals <- mlr::getLearnerParVals
get_learner_predict_type <- mlr::getLearnerPredictType
get_learner_properties <- mlr::getLearnerProperties
get_learner_short_name <- mlr::getLearnerShortName
get_learner_type <- mlr::getLearnerType
get_measure_properties <- mlr::getMeasureProperties
get_mlr_options <- mlr::getMlrOptions
get_multilabel_binary_performances <- mlr::getMultilabelBinaryPerformances
get_nested_tune_results_opt_path_df <- mlr::getNestedTuneResultsOptPathDf
get_nested_tune_results_x <- mlr::getNestedTuneResultsX
get_oob_preds <- mlr::getOOBPreds
get_prediction_dump <- mlr::getPredictionDump
get_prediction_probabilities <- mlr::getPredictionProbabilities
get_prediction_response <- mlr::getPredictionResponse
get_prediction_se <- mlr::getPredictionSE
get_prediction_task_desc <- mlr::getPredictionTaskDesc
get_prediction_truth <- mlr::getPredictionTruth
get_resampling_indices <- mlr::getResamplingIndices
get_rr_dump <- mlr::getRRDump
get_rr_prediction_list <- mlr::getRRPredictionList
get_rr_predictions <- mlr::getRRPredictions
get_rr_task_desc <- mlr::getRRTaskDesc
get_stacked_base_learner_predictions <- mlr::getStackedBaseLearnerPredictions
get_task_class_levels <- mlr::getTaskClassLevels
get_task_costs <- mlr::getTaskCosts
get_task_data <- mlr::getTaskData
get_task_desc <- mlr::getTaskDesc
get_task_feature_names <- mlr::getTaskFeatureNames
get_task_formula <- mlr::getTaskFormula
get_task_id <- mlr::getTaskId
get_task_n_feats <- mlr::getTaskNFeats
get_task_size <- mlr::getTaskSize
get_task_target_names <- mlr::getTaskTargetNames
get_task_targets <- mlr::getTaskTargets
get_task_type <- mlr::getTaskType
get_tune_result <- mlr::getTuneResult
get_tune_result_opt_path <- mlr::getTuneResultOptPath
has_functional_features <- mlr::hasFunctionalFeatures
has_learner_properties <- mlr::hasLearnerProperties
has_measure_properties <- mlr::hasMeasureProperties
has_properties <- mlr::hasProperties
help_learner <- mlr::helpLearner
help_learner_param <- mlr::helpLearnerParam
impute_constant <- mlr::imputeConstant
impute_hist <- mlr::imputeHist
impute_learner <- mlr::imputeLearner
impute_max <- mlr::imputeMax
impute_mean <- mlr::imputeMean
impute_median <- mlr::imputeMedian
impute_min <- mlr::imputeMin
impute_mode <- mlr::imputeMode
impute_normal <- mlr::imputeNormal
impute_uniform <- mlr::imputeUniform
is_failure_model <- mlr::isFailureModel
join_class_levels <- mlr::joinClassLevels
learner_args_to_control <- mlr::learnerArgsToControl
list_filter_methods <- mlr::listFilterMethods
list_learner_properties <- mlr::listLearnerProperties
list_learners <- mlr::listLearners
list_measure_properties <- mlr::listMeasureProperties
list_measures <- mlr::listMeasures
list_task_types <- mlr::listTaskTypes
make_aggregation <- mlr::makeAggregation
make_bagging_wrapper <- mlr::makeBaggingWrapper
make_classification_via_regression_wrapper <- mlr::makeClassificationViaRegressionWrapper
make_classif_task <- mlr::makeClassifTask
make_cluster_task <- mlr::makeClusterTask
make_constant_class_wrapper <- mlr::makeConstantClassWrapper
make_cost_measure <- mlr::makeCostMeasure
make_cost_sens_classif_wrapper <- mlr::makeCostSensClassifWrapper
make_cost_sens_regr_wrapper <- mlr::makeCostSensRegrWrapper
make_cost_sens_task <- mlr::makeCostSensTask
make_cost_sens_weighted_pairs_wrapper <- mlr::makeCostSensWeightedPairsWrapper
make_custom_resampled_measure <- mlr::makeCustomResampledMeasure
make_downsample_wrapper <- mlr::makeDownsampleWrapper
make_dummy_features_wrapper <- mlr::makeDummyFeaturesWrapper
make_extract_fda_feat_method <- mlr::makeExtractFDAFeatMethod
make_extract_fda_feats_wrapper <- mlr::makeExtractFDAFeatsWrapper
make_feat_sel_control_exhaustive <- mlr::makeFeatSelControlExhaustive
make_feat_sel_control_ga <- mlr::makeFeatSelControlGA
make_feat_sel_control_random <- mlr::makeFeatSelControlRandom
make_feat_sel_control_sequential <- mlr::makeFeatSelControlSequential
make_feat_sel_wrapper <- mlr::makeFeatSelWrapper
make_filter <- mlr::makeFilter
make_filter_wrapper <- mlr::makeFilterWrapper
make_fixed_holdout_instance <- mlr::makeFixedHoldoutInstance
make_functional_data <- mlr::makeFunctionalData
make_impute_method <- mlr::makeImputeMethod
make_impute_wrapper <- mlr::makeImputeWrapper
make_learner <- mlr::makeLearner
make_learners <- mlr::makeLearners
